name: mai_calendar_example
description: Example app for the Mai Calendar package

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Local package
  mai_calendar:
    path: ../

  # Dependencies from the main package
  provider: ^6.1.2
  get_it: ^7.6.7
  supabase_flutter: ^2.3.3
  syncfusion_flutter_calendar: ^24.2.8
  syncfusion_flutter_core: ^24.2.8
  syncfusion_flutter_datepicker: ^24.2.8
  intl: ^0.19.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
